// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfnhjmlvewfksmqrmxta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbmhqbWx2ZXdma3NtcXJteHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjM0MzUsImV4cCI6MjA2NTczOTQzNX0.7j6L09v33aI8bkV8eI6eocX4QuNXlWA5sxL8AAMCDxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);